[profile.default]
src = 'src'
out = 'out'
libraries=[]
# via_ir = true
solc_version = '0.8.20'
gas_reports = ["FraudProof"]
# See more config options https://github.com/gakonst/foundry/tree/master/config